### ISSUE TITLE
Repeating Directive not rendering new template

### ISSUE THREAD

**Issue by coeus01** [lorenzofox3/lrInfiniteScroll#13]
I have an issue with this setup:
```html
<div lr-infinite-scroll="loadMore">
    <my-component type='item.type' ng-repeat='item in items'></my-component>
</div>
```
I have a directive inside with different html template for each item type. The infinite scrolling works perfectly but when I change the item array with items with different type the template remains the same.

**Comment by lorenzofox3** [comment]
I don't think that is related to lr-infinite-scroll but rather to the my-component one, have you tried without using lr-infinite-scroll ? do you experiment any issue ?

**Comment by coeus01** [comment]
Hello @lorenzofox3 after all it was my fault, I had the `track by $index` option on
