### ISSUE TITLE
Update release to 1.0.1 to support CommonJS 

### ISSUE THREAD

**Issue by leigh-johnson** [lorenzofox3/lrInfiniteScroll#17]
Heyo :)

First, thanks for writing such a nifty module!

Could you create a release `1.0.1` that points to revision bd8fd2b0953a7d9f6a91070433a963cf4e655a17 so CommonJS imports of this module are supported when installing via Bower? Currently, Bower installers have to write their own `index.js` file after installing.

**Comment by lorenzofox3** [comment]
Hello.
I am not sure to understand. The commit you are referring to is about doc changes is not it ?

**Comment by leigh-johnson** [comment]
You need to create a new release points to that commit sha, so people who `bower install` your module can pull in the latest changes. Currently you have to clone the repo to snag the latest

**Comment by prismsoundzero** [comment]
There is an issue with the new release: "main" property should remain  "lrInfiniteScroll.js" in bower.json
